# Python Data Science Handbook (JVP)- Chapter 2

## December 12, 2019

In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

In [7]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
type(L2[0])

str

In [9]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [10]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
import numpy as np

In [12]:
# integer array:
np.array([1, 4, 2, 9, 3])

array([1, 4, 2, 9, 3])

In [13]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [14]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [15]:
# nested list result in multidimensional arrays
np.array([range(i, i +3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [16]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.0145873 , 0.84499107, 0.34350547],
       [0.1879739 , 0.43422933, 0.27443523],
       [0.06931177, 0.89604527, 0.42260509]])

In [22]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation of 1
np.random.normal(0, 1, (3, 3))

array([[ 0.31228406, -1.00638618, -0.16630843],
       [ 1.03333692, -0.86294087,  1.36731929],
       [ 0.4861314 , -2.4244098 , -0.67461894]])

In [23]:
# Create a 3x3 array of random integers in the interval [0, 10]
np.random.randint(0, 10, (3, 3))

array([[9, 5, 7],
       [5, 7, 6],
       [5, 4, 4]])

In [24]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Create an unitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

### Important Standard Numpy data types table can be found on page 41

In [27]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [28]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [29]:
print("dtype: ", x3.dtype)

dtype:  int32


In [30]:
print("itemsize: ", x3.itemsize, "bytes")
print("ndites: ", x3.nbytes, "bytes")

itemsize:  4 bytes
ndites:  240 bytes


In [33]:
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
x1[0]

5

In [35]:
x1[4]

7

In [36]:
x1[-1]

9

In [37]:
x1[-2]

7

In [38]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [39]:
x2[0, 0]

3

In [40]:
x2[2, 0]

1

In [41]:
x2[2, -1]

7

In [42]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [43]:
x1[0] = 3.14149 # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])